# Generated by Django 3.0.8 on 2020-07-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('value1', models.CharField(max_length=4096)),
                ('value2', models.FloatField()),
                ('value3', models.BooleanField()),
                ('creationDate', models.BigIntegerField()),
                ('lastModificationDate', models.BigIntegerField()),
            ],
        ),
    ]
